name: leaderboard-python

services:
  app:  
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: python ./src/manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
