# Generated by Django 5.2.2 on 2025-06-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('latest_submission_date', models.DateField()),
                ('num_submissions_included', models.IntegerField()),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.contestant')),
            ],
            options={
                'ordering': ['-total_score', '-num_submissions_included'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.competition')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='RankingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_submissions', to='data.ranking')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.submission')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('contestant', 'competition', 'date'), name='unique_submission'),
        ),
        migrations.AddConstraint(
            model_name='rankingsubmission',
            constraint=models.UniqueConstraint(fields=('ranking', 'submission'), name='unique_ranking_submission'),
        ),
    ]
