# Generated by Django 5.2.2 on 2025-06-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('num_submissions_included', models.IntegerField()),
                ('latest_submission_date', models.DateField()),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='RankingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.contestant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.submission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ranking', 'submission'), name='unique_ranking_submission')],
            },
        ),
    ]
