# Generated by Django 5.2.2 on 2025-06-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_ranking_rankingsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-total_score', '-num_submissions_included']},
        ),
        migrations.AlterField(
            model_name='rankingsubmission',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_submissions', to='data.ranking'),
        ),
    ]
